import {NAME} from './constants';

export const FIRE_WEAPON = `${NAME}/FIRE_WEAPON`;
export const CHANGE_MODE = `${NAME}/CHANGE_MODE`;
export const RESET_BOARD = `${NAME}/RESET_BOARD`;

export const SERVER_CONNECT_PLAYER = `server/${NAME}/SERVER_CONNECT_PLAYER`;
export const SERVER_DISCONNECT_PLAYER = `server/${NAME}/SERVER_DISCONNECT_PLAYER`;
export const CONNECT_PLAYER_SUCCESS = `${NAME}/CONNECT_PLAYER_SUCCESS`;
export const DISCONNECT_PLAYER_SUCCESS = `${NAME}/DISCONNECT_PLAYER_SUCCESS`;
export const UPDATE_PLAYERS_ONLINE = `${NAME}/UPDATE_PLAYERS_ONLINE`;
export const FIRE_WEAPON_REMOTE = `server/${NAME}/FIRE_WEAPON_REMOTE`;






export const FIRE_WEAPON_REMOTE_SUCCESS = `${NAME}/FIRE_WEAPON_REMOTE_SUCCESS`;

export const SEND_WINNER = `${NAME}/SEND_WINNER`;

